WIP: Extract functionality to functions, sleep on except
FriskByBergen/RPiParticle pull request #61
Opened 2016-10-11 18:53 UTC by pgdr

* Moved collect, post, upgrade to functions
* catch SerialException
* on exception, sleep exponentially longer (up to 1 day)

2016-10-11 18:54 UTC, pgdr commented
Alternative to Request #60, this also tries to solve Issue #59.

2016-10-11 18:56 UTC, pgdr commented
@semafor review needed

2016-10-11 19:06 UTC, semafor commented on bin/fby_client
>              exc_type, exc_value, exc_tb = sys.exc_info()
EXCEPTION_COUNT++

2016-10-11 19:11 UTC, semafor commented on bin/fby_client
> +            time.sleep(min(timeout, day))
Kanskje det er bedre at EXCEPTION_COUNT fører til at man _ikke_ poster, i stedet for å sove? Argumentet er at det har en kost å spamme servere, men det har ingen kost å kaste exceptions. Dette gir og eier av klient mulighet til å lese systemd logs for å finne feilen.

2016-10-11 19:11 UTC, semafor requested changes
Fint! Et par kommentarer følger.

2016-10-12 13:35 UTC, joakim-hove commented on bin/fby_client
> +    except SerialException as se:
Siden vi nå veldig eksplisitt håndterer `SerialException` synes jeg kanskje det skulle være `SAMPLE_ERROR_COUNT` el.lign. og ikke `EXCEPTION_COUNT`.

2016-10-12 13:36 UTC, joakim-hove commented on bin/fby_client
> +def downloadConfig():
Siden denne gjør enn bare å laste ned ny config vil jeg foreslå f.eks. navnet: `updateClient()`el.lign.

2016-10-13 16:33 UTC, pgdr commented on bin/fby_client
> +    except SerialException as se:
Ja, men det er fortsatt en telling av exceptions, ettersom jeg ønsker å øke telleren ved arbitrære exceptions.

2016-10-13 16:34 UTC, pgdr commented on bin/fby_client
> +def downloadConfig():
Godt poeng. Fixed.

2016-10-13 16:35 UTC, pgdr commented
> but I would like [...] also include an outer `try: catch Exception` to try to ensure that all exceptions are logged.
I think every exceptions will be logged, the only thing that is outside the `try` now is the call to `time.sleep`.

2016-10-13 19:29 UTC, joakim-hove commented
Takk - inn går den!

2016-10-13 19:29 UTC, merged